apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app   # <--- Corrigido aqui
data:
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mensagensdb"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"

