apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: database
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
